# MyActuator X4-36 EtherCAT Configuration - Joint 5 Motor (REVERSED)
# EtherCAT slave position 4, offset: 0.0

vendor_id: 0x00202008
product_id: 0x00000000
assign_activate: 0x0300

auto_fault_reset: true
auto_state_transitions: true
mode_of_operation: 10

sdo:
  - {index: 0x6072, sub_index: 0, type: uint16, value: 190}  # 2 Nm max torque

rpdo:
  - index: 0x1600
    channels:
      - {index: 0x6040, sub_index: 0, type: uint16, command_interface: ~, default: 0}
      - {index: 0x607a, sub_index: 0, type: int32, command_interface: position, factor: -41721.6, default: 0}
      - {index: 0x60ff, sub_index: 0, type: int32, command_interface: velocity, factor: -41721.6, default: 0}
      - {index: 0x6071, sub_index: 0, type: int16, command_interface: effort, factor: -95.24, default: 0}
      - {index: 0x6072, sub_index: 0, type: int16, command_interface: ~, default: 190}
      - {index: 0x6060, sub_index: 0, type: int8, command_interface: ~, default: 10}
      - {index: 0x5ff1, sub_index: 0, type: int8, command_interface: ~, default: 0}

tpdo:
  - index: 0x1a00
    channels:
      - {index: 0x6041, sub_index: 0, type: uint16, state_interface: ~}
      - {index: 0x6064, sub_index: 0, type: int32, state_interface: position, factor: -2.397e-5, offset: 0.0}
      - {index: 0x606c, sub_index: 0, type: int32, state_interface: velocity, factor: -2.397e-5}
      - {index: 0x6077, sub_index: 0, type: int16, state_interface: effort, factor: 0.0105}
      - {index: 0x603f, sub_index: 0, type: uint16, state_interface: ~}
      - {index: 0x6061, sub_index: 0, type: int8, state_interface: ~}
      - {index: 0x5ff2, sub_index: 0, type: int8, state_interface: ~}
